chrome/browser/about_flags.cc
chrome/browser/chrome_browser_main_win.cc
chrome/browser/chromeos/login/chrome_restart_request.cc
content/browser/gpu/gpu_process_host.cc
content/browser/plugin_process_host.cc
content/browser/renderer_host/render_process_host_impl.cc
content/browser/renderer_host/render_widget_host_view_browsertest.cc
content/browser/zygote_host/zygote_host_impl_linux.cc
content/shell/app/shell_main_delegate.cc
ui/gfx/display.cc
ui/gfx/font_render_params_linux.cc
ui/gfx/switches.cc
ui/gfx/switches.h
ui/gfx/win/dpi.cc
